### PR TITLE
PostgreSql migration+one to many relation for User-LocationAttributes

### PR DESCRIPTION
**Pull request by SilviuRusu3**

### CODE REVIEW

**Comment by SilviuRusu3** [comment]
I think I managed to do the migration to Postgres and define the one to many relation between User and LocationAttributes. The only downside is that now the CRUD on LocationAttributes doesn't work. I will fix this next.

**Comment by SilviuRusu3** [comment]
Now I got everything working. So I have LocationAttributes for every User and the CRUD works.

**Review by andreisamoila74 — APPROVED** [review]
why there are so many files? are there all generated because of the migration?

**Comment by SilviuRusu3** [comment]
Yes. I only added a single class and the rest of the files are from migrations.

**Pull request merged**
